LEARNING THE TENSORFLOW DATA API

1. CSV DATA FORMAT

In [11]:
import tensorflow as tf

In [12]:
data = tf.range(10)
dataset = tf.data.Dataset.from_tensor_slices(data)

In [13]:
def print_dataset(dataset):
    for data in dataset:
        print(data)

CHAINING TRANSFORMATIONS

In [14]:
dataset = dataset.repeat(3).batch(7)
print_dataset(dataset)

tf.Tensor([0 1 2 3 4 5 6], shape=(7,), dtype=int32)
tf.Tensor([7 8 9 0 1 2 3], shape=(7,), dtype=int32)
tf.Tensor([4 5 6 7 8 9 0], shape=(7,), dtype=int32)
tf.Tensor([1 2 3 4 5 6 7], shape=(7,), dtype=int32)
tf.Tensor([8 9], shape=(2,), dtype=int32)


In [16]:
dataset = dataset.repeat(3).batch(7,drop_remainder=True)
# print_dataset(dataset)

MAP METHOD

In [18]:
dataset = dataset.map(lambda x: x *2,num_parallel_calls=4)#num_parallel_calls param helps speed things up by spawning mutiple threads
# print_dataset(dataset)

"""APPLY METHOD:

NOTE: WHILE MAP DOES TRANSFORMATIONS TO EVERY INDIVIDUAL DATA IN THE DATASET APPLY DOES IT TO THE WHOLE DATASET AS AN ENTTY"""

In [20]:
dataset = dataset.apply(lambda x :tf.data.Dataset.unbatch(x))
# dataset = dataset.unbatch()
# print_dataset(dataset)

FILTER METHOD

In [23]:
# dataset = dataset.filter(lambda x : x<10)
# print_dataset(dataset)

TAKE METHOD

In [ ]:
for data in dataset.take(5):
    print(data)

SHUFFLE METHOD

In [ ]:
new_dataset = tf.data.Dataset.range(10).repeat(7)
new_dataset = new_dataset.shuffle(5,seed=42).repeat(2).batch(7)
for item in new_dataset:
    print(item)

tf.Tensor([0 2 3 6 7 9 4], shape=(7,), dtype=int64)
tf.Tensor([5 0 1 1 8 6 5], shape=(7,), dtype=int64)
tf.Tensor([4 8 7 1 2 3 0], shape=(7,), dtype=int64)
tf.Tensor([5 4 2 7 8 9 1], shape=(7,), dtype=int64)
tf.Tensor([3 6 0 4 6 3 9], shape=(7,), dtype=int64)
tf.Tensor([9 2 7 5 3 1 5], shape=(7,), dtype=int64)
tf.Tensor([6 0 2 7 4 1 2], shape=(7,), dtype=int64)
tf.Tensor([3 8 8 4 9 0 6], shape=(7,), dtype=int64)
tf.Tensor([0 9 2 3 7 1 4], shape=(7,), dtype=int64)
tf.Tensor([5 6 7 8 5 8 9], shape=(7,), dtype=int64)
tf.Tensor([3 5 2 1 8 4 0], shape=(7,), dtype=int64)
tf.Tensor([1 2 3 7 9 5 0], shape=(7,), dtype=int64)
tf.Tensor([7 4 0 9 6 8 1], shape=(7,), dtype=int64)
tf.Tensor([2 6 6 4 9 0 1], shape=(7,), dtype=int64)
tf.Tensor([3 7 8 5 4 2 3], shape=(7,), dtype=int64)
tf.Tensor([5 8 0 7 1 4 5], shape=(7,), dtype=int64)
tf.Tensor([2 3 9 6 9 8 1], shape=(7,), dtype=int64)
tf.Tensor([6 0 7 2 5 6 8], shape=(7,), dtype=int64)
tf.Tensor([4 0 9 7 4 5 2], shape=(7,), dtype=int64)
tf.Tensor([6

READING FILES (CSV) FROM FILE SYSTEM

USING LIST FILES

In [ ]:
file_dataset = tf.data.Dataset.list_files("C:\\Users\\Mark Mwema\\Desktop\\DeepLearning\\Churn_Modelling.csv")
file_dataset

<_ShuffleDataset element_spec=TensorSpec(shape=(), dtype=tf.string, name=None)>

Reading from the list files using interleave method to get the text dataset

In [ ]:
text_data = file_dataset.interleave(
    lambda file_path: tf.data.TextLineDataset(file_path).skip(1),
    cycle_length=1,
    name="Churn_modelling_data"
)

In [ ]:
for data in text_data.take(5):
    print(data)

tf.Tensor(b'1,15634602,Hargrave,619,France,Female,42,2,0,1,1,1,101348.88,1', shape=(), dtype=string)
tf.Tensor(b'2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0', shape=(), dtype=string)
tf.Tensor(b'3,15619304,Onio,502,France,Female,42,8,159660.8,3,1,0,113931.57,1', shape=(), dtype=string)
tf.Tensor(b'4,15701354,Boni,699,France,Female,39,1,0,2,0,0,93826.63,0', shape=(), dtype=string)
tf.Tensor(b'5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.1,0', shape=(), dtype=string)


In [ ]:
text_data

<_InterleaveDataset element_spec=TensorSpec(shape=(), dtype=tf.string, name=None)>

2. TF-RECORD FORMAT

In [ ]:
file_path = """C:\\Users\\Mark Mwema\\Desktop\\DeepLearning\\myTFRECORD.tfrecord"""

In [ ]:
with tf.io.TFRecordWriter(file_path) as f:
    f.write("This is my first tensorflow record data format")
    f.write("I long for the day I am able to create projects with this that I learn")
    f.write("----------------THANK OU JESUS FOR THIS OPPOURTUNITY-----------------")

In [ ]:
tfrecord_dataset = tf.data.TFRecordDataset(file_path)
for data in tfrecord_dataset:
    print(data)

tf.Tensor(b'This is my first tensorflow record data format', shape=(), dtype=string)
tf.Tensor(b'I long for the day I am able to create projects with this that I learn', shape=(), dtype=string)
tf.Tensor(b'----------------THANK OU JESUS FOR THIS OPPOURTUNITY-----------------', shape=(), dtype=string)


In [ ]:
options = tf.io.TFRecordOptions(compression_type="GZIP")

In [25]:
with tf.io.TFRecordWriter(file_path,options=options) as f:
    f.write("2.")
    f.write("This is my first tensorflow record data format")
    f.write("I long for the day I am able to create projects with this that I learn")
    f.write("----------------THANK YOU JESUS FOR THIS OPPOURTUNITY-----------------")

In [28]:
tfrecord_dataset = tf.data.TFRecordDataset(file_path,compression_type="GZIP",num_parallel_reads=2)
for data in tfrecord_dataset:
    print(data)

tf.Tensor(b'2.', shape=(), dtype=string)
tf.Tensor(b'This is my first tensorflow record data format', shape=(), dtype=string)
tf.Tensor(b'I long for the day I am able to create projects with this that I learn', shape=(), dtype=string)
tf.Tensor(b'----------------THANK YOU JESUS FOR THIS OPPOURTUNITY-----------------', shape=(), dtype=string)


PROCOL-BUFFERS (PROTOBUF)